version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama2000
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  anythingllm:
    image: mintplexlabs/anythingllm:latest 22222
    container_name: anythingllm
    ports:
      - "3002:3002"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=A2hQ10sPo0
      - AUTH_MODE=local
      - ADMIN_EMAIL=leoinkling92@gmail.com       
      - ADMIN_PASSWORD=A2hQ10sPo0
    volumes:
      - anythingllm_data:/app/server/storage
    restart: unless-stopped
    command: /bin/sh -c "rm -rf /app/server/storage/sessions/* && node server.js"

volumes:
  ollama_data:
  anythingllm_data:
